name: .NET

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build-test-pack:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore PolyhydraGames.IMVDB.Test.sln

      - name: Build
        run: dotnet build PolyhydraGames.IMVDB.Test.sln --no-restore

      - name: Test
        run: dotnet test PolyhydraGames.IMVDB.Test.sln --no-restore --no-build --verbosity normal

      - name: Pack
        run: dotnet pack PolyhydraGames.IMVDB.Api/PolyhydraGames.IMVDB.csproj --configuration Release --no-restore --output ./artifacts/package

      - name: Upload package artifact
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: ./artifacts/package/*.nupkg
